export const conditionData = {
  "knee-pain": {
    title: "Knee Pain Treatment",
    subtitle: "Comprehensive diagnosis and robotic intervention for acute and chronic knee pain.",
    seoKeywords: "knee pain treatment in hyderabad, chronic knee pain doctor, knee swelling specialist",
    symptoms: ["Pain when climbing stairs", "Morning stiffness", "Swelling after activity", "Catching or locking sensation"],
    recommendedProcedure: "robotic-knee-arthroplasty",
    specialistName: "Dr. Amith Reddy",
    specialistRole: "Lead – Robotic Knee Arthroplasty Program",
    anatomyText: "Knee pain is a symptom, not a diagnosis. It can stem from mechanical issues like a torn meniscus or structural degradation like osteoarthritis. Our board utilizes 3D CT mapping and MRI to pinpoint the exact pain generator before recommending conservative or robotic surgical intervention."
  },
  "shoulder-pain": {
    title: "Shoulder Pain & Stiffness Treatment",
    subtitle: "Advanced arthroscopic solutions for rotator cuff tears, frozen shoulder, and impingement.",
    seoKeywords: "shoulder pain treatment hyderabad, frozen shoulder doctor, shoulder impingement specialist",
    symptoms: ["Inability to sleep on the affected side", "Pain reaching overhead", "Weakness lifting objects", "Aching at rest"],
    recommendedProcedure: "rotator-cuff-repair",
    specialistName: "Dr. Deepthi Nandan Reddy",
    specialistRole: "HOD – Upper Extremity & Revision Unit",
    anatomyText: "The shoulder is the most mobile joint in the body, but this mobility comes at the cost of stability. Pain often originates in the rotator cuff tendons. Ignoring chronic shoulder pain can lead to massive tendon retraction and irreversible muscle atrophy."
  },
  "back-pain": {
    title: "Back Pain & Spine Treatment",
    subtitle: "Minimally invasive decompression and stabilization for lumbar and cervical spine conditions.",
    seoKeywords: "back pain treatment in hyderabad, spine specialist, slipped disc treatment",
    symptoms: ["Radiating pain down the leg (sciatica)", "Numbness or tingling in the feet", "Pain worse with bending or sitting", "Muscle spasms"],
    recommendedProcedure: "spine-surgery",
    specialistName: "Precision Spine Board",
    specialistRole: "Spinal Care Unit",
    anatomyText: "Back pain can arise from muscular strain, herniated discs, or spinal stenosis (narrowing of the spinal canal). Our diagnostic pipeline identifies the specific nerve compression site to deliver targeted, minimally invasive decompression."
  },
  "hip-pain": {
    title: "Hip Pain & Stiffness Treatment",
    subtitle: "Muscle-sparing reconstruction for hip arthritis and impingement.",
    seoKeywords: "hip pain treatment hyderabad, hip arthritis doctor, groin pain specialist",
    symptoms: ["Pain in the groin", "Difficulty putting on shoes and socks", "Limping", "Pain transferring from sitting to standing"],
    recommendedProcedure: "robotic-hip-arthroplasty",
    specialistName: "Dr. Nitish Bhan",
    specialistRole: "Lead – DAA Hip & Pelvic Reconstruction",
    anatomyText: "True hip joint pain is typically felt in the groin, not the outer hip. It is often the result of osteoarthritis or femoroacetabular impingement (FAI). We specialize in the Direct Anterior Approach (DAA) to resolve hip pain without detaching major muscles."
  },
  "sports-injuries": {
    title: "Sports Injury Treatment",
    subtitle: "Accelerated biological restoration and arthroscopic repair for athletic trauma.",
    seoKeywords: "sports injury treatment in hyderabad, sports medicine doctor, ligament tear specialist",
    symptoms: ["Sudden 'pop' during play", "Immediate swelling", "Joint instability or 'giving way'", "Inability to bear weight"],
    recommendedProcedure: "acl-pcl-reconstruction",
    specialistName: "Dr. Ravi Teja Rudraraju",
    specialistRole: "Lead – Joint Preservation & Sports Medicine",
    anatomyText: "Athletic injuries demand a higher level of precision. Returning to high-velocity sports requires an anatomically perfect reconstruction and rigorous, data-driven kinetic profiling using our VALD Performance systems."
  },
  "shoulder-instability": { aliasOf: "shoulder-pain" },
  "frozen-shoulder": { aliasOf: "shoulder-pain" },
  "sciatica-treatment": { aliasOf: "back-pain" },
  "joint-pain": { aliasOf: "knee-pain" },
  "lower-waist-pain": { aliasOf: "shoulder-pain" },
  "allergy-to-metal-orthopedic-implants": { aliasOf: "shoulder-pain" },
  "metal-implants-cause-any-side-effects": { aliasOf: "shoulder-pain" },
  "symptoms-of-body-rejecting-metal-plate": { aliasOf: "shoulder-pain" },
  "symptoms-of-body-rejecting-titanium-plate": { aliasOf: "shoulder-pain" },
  "broken-shoulder-in-elderly": { aliasOf: "shoulder-pain" },
  "shoulder-bone-fracture": { aliasOf: "shoulder-pain" },
  "shoulder-bone-injury": { aliasOf: "shoulder-pain" },
  "shoulder-fracture-symptoms": { aliasOf: "shoulder-pain" },
  "shoulder-fractures": { aliasOf: "shoulder-pain" },
  "shoulder-joint-fracture": { aliasOf: "shoulder-pain" },
  "causes-of-shoulder-pain-in-elderly": { aliasOf: "shoulder-pain" },
  "chronic-shoulder-pain-elderly": { aliasOf: "shoulder-pain" },
  "deal-with-shoulder-pain": { aliasOf: "shoulder-pain" },
  "elder-shoulder-pain": { aliasOf: "shoulder-pain" },
  "body-pains": { aliasOf: "shoulder-pain" },
  "can-vitamin-d-deficiency-cause-joint-pain-and-swelling": { aliasOf: "shoulder-pain" },
  "does-vitamin-d-deficiency-cause-chronic-pain": { aliasOf: "shoulder-pain" },
  "how-to-spot-a-vitamin-d-deficiency": { aliasOf: "shoulder-pain" },
  "vitamin-d-deficiency-cause-body-pains": { aliasOf: "shoulder-pain" },
  "hyderabad": { aliasOf: "shoulder-pain" },
  "ligament-injuries": { aliasOf: "shoulder-pain" },
  "leg-ankle-ligament-injury": { aliasOf: "shoulder-pain" },
  "leg-sprains": { aliasOf: "shoulder-pain" },
  "what-is-the-recovery-period-after-a-dislocated-shoulder": { aliasOf: "shoulder-pain" },
  "shoulder-problem": { aliasOf: "shoulder-pain" },
  "dislocated-shoulder": { aliasOf: "shoulder-pain" },
  "intense-shoulder-pain": { aliasOf: "shoulder-pain" },
  "rheumatoid-arthritis": { aliasOf: "shoulder-pain" },
  "shoulder-arthritis": { aliasOf: "shoulder-pain" },
  "shoulder-injury": { aliasOf: "shoulder-pain" },
  "shoulder-sprain": { aliasOf: "shoulder-pain" },
  "signs-and-symptoms-that-indicates-a-dislocated-shoulder-in-children": { aliasOf: "shoulder-pain" },
  "when-do-i-approach-pediatric-orthopedician": { aliasOf: "shoulder-pain" },
  "shoulder-problems": { aliasOf: "shoulder-pain" },
  "physical-therapist": { aliasOf: "shoulder-pain" },
  "shoulder-joint-problems": { aliasOf: "shoulder-pain" },
  "arthritis-of-the-shoulder": { aliasOf: "shoulder-pain" },
  "causes-of-shoulder-degenerative-disease-pain": { aliasOf: "shoulder-pain" },
  "degenerative-diseases-of-shoulder-joints": { aliasOf: "shoulder-pain" },
  "how-to-get-rid-of-degenerative-diseases-of-shoulder-joints": { aliasOf: "shoulder-pain" },
  "osteoarthritis-in-shoulder": { aliasOf: "shoulder-pain" },
  "shoulder-joints": { aliasOf: "shoulder-pain" },
  "types-of-degenerative-diseases-in-shoulder-joint": { aliasOf: "shoulder-pain" },
  "full-shoulder-workout": { aliasOf: "shoulder-pain" },
  "most-effective-shoulder-exercises": { aliasOf: "shoulder-pain" },
  "shoulder-exercises-at-home": { aliasOf: "shoulder-pain" },
  "shoulder-exercises-for-beginners": { aliasOf: "shoulder-pain" },
  "shoulder-exercises-for-women": { aliasOf: "shoulder-pain" },
  "shoulder-injuries": { aliasOf: "shoulder-pain" },
  "dislocated-joint": { aliasOf: "shoulder-pain" },
  "functions-of-glenohumeral-joint": { aliasOf: "shoulder-pain" },
  "glenohumeral-joint": { aliasOf: "shoulder-pain" },
  "shoulder-joint": { aliasOf: "shoulder-pain" },
  "shoulder-arthroscopic": { aliasOf: "shoulder-pain" },
  "dislocated-shoulder-causes": { aliasOf: "shoulder-pain" },
  "dislocated-shoulder-recovery-process": { aliasOf: "shoulder-pain" },
  "dislocated-shoulder-symptoms": { aliasOf: "shoulder-pain" },
  "arthroscopic-procedure": { aliasOf: "shoulder-pain" },
  "broken-shoulder": { aliasOf: "shoulder-pain" },
  "types-of-shoulder-fractures": { aliasOf: "shoulder-pain" },
  "immediately-after-your-injury": { aliasOf: "shoulder-pain" },
  "tendon-transfer": { aliasOf: "shoulder-pain" },
  "pain-management": { aliasOf: "shoulder-pain" },
  "eid-mubarak-wishes": { aliasOf: "shoulder-pain" },
  "dislocated-shoulder-in-hyderabad": { aliasOf: "shoulder-pain" },
  "dislocated-shoulder-pain-relief": { aliasOf: "shoulder-pain" },
  "independence-day-wishes-poster": { aliasOf: "shoulder-pain" },
  "ganesh-chaturthi-wishes-poster": { aliasOf: "shoulder-pain" },
  "physical-therapist-for-dislocated-shoulder": { aliasOf: "shoulder-pain" },
  "cost-of-dislocated-shoulder-in-hyderabad": { aliasOf: "shoulder-pain" },
  "blog": { aliasOf: "shoulder-pain" },
  "diwali-wishes-poster": { aliasOf: "shoulder-pain" },
  "arthroscopic-superior-capsular-reconstruction-in-hyderabad": { aliasOf: "shoulder-pain" },
  "shoulder": { aliasOf: "shoulder-pain" },
  "rheumatoid-arthritis-shoulder": { aliasOf: "shoulder-pain" },
  "shoulder-arthritis-exercises": { aliasOf: "shoulder-pain" },
  "shoulder-pain-cure-in-hyderabad": { aliasOf: "shoulder-pain" },
  "shoulder-tendonitis-exercises": { aliasOf: "shoulder-pain" },
  "dislocated-shoulder-cost-in-hyderabad": { aliasOf: "shoulder-pain" },
  "3-stages-of-frozen-shoulder": { aliasOf: "frozen-shoulder" },
  "freezing-stage-frozen-shoulder": { aliasOf: "frozen-shoulder" },
  "frozen-shoulder-problem": { aliasOf: "frozen-shoulder" },
  "frozen-shoulder-stage": { aliasOf: "frozen-shoulder" },
  "signs-and-symptoms-of-frozen-shoulder": { aliasOf: "frozen-shoulder" },
  "thawing-frozen-shoulder-stage": { aliasOf: "frozen-shoulder" },
  "causes-of-frozen-shoulder": { aliasOf: "frozen-shoulder" },
  "frozen-shoulder-symptoms": { aliasOf: "frozen-shoulder" },
  "dysfunction-of-a-frozen-shoulder": { aliasOf: "frozen-shoulder" },
  "who-gets-frozen-shoulder": { aliasOf: "frozen-shoulder" },
  "causes-and-symptoms-of-frozen-shoulder": { aliasOf: "frozen-shoulder" },
  "facts-about-frozen-shoulder": { aliasOf: "frozen-shoulder" },
  "tips-to-fall-good-sleep-with-frozen-shoulder": { aliasOf: "frozen-shoulder" },
  "why-does-frozen-shoulder-pain-get-deeper-at-night": { aliasOf: "frozen-shoulder" },
  "8-frozen-shoulder-exercises-for-quick-relief": { aliasOf: "frozen-shoulder" },
  "exercises-and-stretches-for-a-frozen-shoulder": { aliasOf: "frozen-shoulder" },
  "exercises-for-a-frozen-shoulder": { aliasOf: "frozen-shoulder" },
  "exercises-to-recover-quickly-from-frozen-shoulder": { aliasOf: "frozen-shoulder" },
  "frozen-shoulder-rotator-cuff": { aliasOf: "frozen-shoulder" },
  "what-to-do-with-frozen-shoulder-to-recover-quickly": { aliasOf: "frozen-shoulder" },
  "frozen-shoulder-exericse-tips-you-need-to-keep-in-mind": { aliasOf: "frozen-shoulder" },
  "frozen-shoulder-exercises": { aliasOf: "frozen-shoulder" },
  "symptoms-of-frozen-shoulder": { aliasOf: "frozen-shoulder" },
  "different-stages-of-frozen-shoulder": { aliasOf: "frozen-shoulder" },
  "physiotheraphy-for-frozen-shoulder": { aliasOf: "frozen-shoulder" },
  "frozen-shoulder-in-hyderabad": { aliasOf: "frozen-shoulder" },
  "causes-of-rotator-cuff-problems": { aliasOf: "shoulder-pain" },
  "rotator-cuff": { aliasOf: "shoulder-pain" },
  "rotator-cuff-injury": { aliasOf: "shoulder-pain" },
  "rotator-cuff-problems": { aliasOf: "shoulder-pain" },
  "symptoms-of-rotator-cuff-problems": { aliasOf: "shoulder-pain" },
  "rotator-cuff-injuries": { aliasOf: "shoulder-pain" },
  "rotator-cuff-tear": { aliasOf: "shoulder-pain" },
  "rotator-cuff-recovery": { aliasOf: "shoulder-pain" },
  "rotator-cuff-tear-recovery-time": { aliasOf: "shoulder-pain" },
  "arthroscopic-rotator-cuff": { aliasOf: "shoulder-pain" },
  "avoid-rotator-cuff-injury": { aliasOf: "shoulder-pain" },
  "diagnosis-of-rotator-cuff-injuries": { aliasOf: "shoulder-pain" },
  "how-treat-rotator-cuff-injury-using-arthroscope": { aliasOf: "shoulder-pain" },
  "prevention-of-rotator-cuff-injuries": { aliasOf: "shoulder-pain" },
  "rotator-cuff-injury-prevention": { aliasOf: "shoulder-pain" },
  "rotator-cuff-tear-prevention": { aliasOf: "shoulder-pain" },
  "causes-and-symptoms-of-rotator-cuff-tears-injury": { aliasOf: "shoulder-pain" },
  "rotator-cuff-tears": { aliasOf: "shoulder-pain" },
  "rotator-cuff-tears-diagnosis": { aliasOf: "shoulder-pain" },
  "shoulder-rotator-cuff-injury": { aliasOf: "shoulder-pain" },
  "causes-of-rotator-cuff-tear": { aliasOf: "shoulder-pain" },
  "symptoms-of-rotator-cuff-tear": { aliasOf: "shoulder-pain" },
  "shoulder-rotator-cuff-tear": { aliasOf: "shoulder-pain" },
  "rotator-cuff-tear-cost-in-hyderabad": { aliasOf: "shoulder-pain" },
  "recurrent-shoulder-dislocation": { aliasOf: "shoulder-instability" },
  "anterior-dislocation": { aliasOf: "shoulder-instability" },
  "causes-of-shoulder-dislocation": { aliasOf: "shoulder-instability" },
  "posterior-dislocation": { aliasOf: "shoulder-instability" },
  "shoulder-dislocation": { aliasOf: "shoulder-instability" },
  "shoulder-dislocation-by-sports-injuries": { aliasOf: "shoulder-instability" },
  "types-of-shoulder-dislocation": { aliasOf: "shoulder-instability" },
  "shoulder-dislocation-injuries": { aliasOf: "shoulder-instability" },
  "common-type-of-shoulder-dislocation": { aliasOf: "shoulder-instability" },
  "recurrent-shoulder-dislocation-condition": { aliasOf: "shoulder-instability" },
  "shoulder-dislocation-symptoms": { aliasOf: "shoulder-instability" },
  "pediatric-shoulder-dislocation": { aliasOf: "shoulder-instability" },
  "permanant-solution-for-shoulder-dislocation": { aliasOf: "shoulder-instability" },
  "right-shoulder-dislocation": { aliasOf: "shoulder-instability" },
  "shoulder-dislocation-problem": { aliasOf: "shoulder-instability" },
  "shoulder-operation-for-dislocation": { aliasOf: "shoulder-instability" },
  "shoulder-joint-dislocation": { aliasOf: "shoulder-instability" },
  "types-of-surgeries-for-shoulder-dislocation": { aliasOf: "shoulder-instability" },
  "symptoms-of-shoulder-dislocation": { aliasOf: "shoulder-instability" },
  "shoulder-dislocation-in-hyderabad": { aliasOf: "shoulder-instability" },
  "shoulder-dislocation-emergency-management": { aliasOf: "shoulder-instability" },
  "acl": { aliasOf: "knee-pain" },
  "acl-reconstruction": { aliasOf: "knee-pain" },
  "acl-rupture": { aliasOf: "knee-pain" },
  "knee-problems": { aliasOf: "knee-pain" },
  "acl-ligament-tear": { aliasOf: "knee-pain" },
  "fixed-acl-ligament-tear": { aliasOf: "knee-pain" },
  "partial-acl-tear": { aliasOf: "knee-pain" },
  "causes-and-symptoms-of-acl-injury": { aliasOf: "knee-pain" },
  "knee-ligament": { aliasOf: "knee-pain" },
  "knee-ligament-correction": { aliasOf: "knee-pain" },
  "symptoms-of-sports-injuries": { aliasOf: "sports-injuries" },
  "shoulder-injuries-in-sports": { aliasOf: "sports-injuries" },
  "sports-injury-rehabilitation-center-in-hyderabad": { aliasOf: "sports-injuries" },
  "lower-back-hip-pain": { aliasOf: "back-pain" },
  "lower-back-muscle-pain": { aliasOf: "back-pain" },
  "lower-back-pain": { aliasOf: "back-pain" },
  "lower-spine-pain": { aliasOf: "back-pain" },
};
