export const doctorDetails = {
  "deepthi-nandan-reddy": {
    name: "Dr. Deepthi Nandan Reddy",
    role: "Lead – Upper Limb & Revision Arthroplasty Program",
    unitName: "Upper Extremity & Revision Unit",
    platform: "Mayo Clinic Faculty | NHS Consultant Pedigree",
    specificVolume: "4,000+ Complex Shoulder Reconstructions",
    title: "HOD - Senior Consultant Orthopaedic Surgeon",
    focus: "Global Expert in Upper Limb & Revision Arthroplasty",
    image: "/doctors/doc_deepthi.png",
    appointmentLink: "https://www.apollo247.com/doctors/dr-deepthi-nandan-reddy-eccd06f7-a7c4-4f40-a212-63a2d62450c7?source=Listing_Page",
    bio: "Dr. Deepthi Nandan Reddy is the Head of the Department and a clinical powerhouse with over three decades of international experience. As one of the most decorated upper limb surgeons globally and a former NHS Consultant, he sets the international standard for complex Shoulder and Elbow reconstructions. He was awarded the prestigious Mayo Clinic Travelling Fellowship, marking him as a leader in structural joint repairs.",
    experience: "30+ Years",
    procedures: "15,000+",
    conditions: ["Shoulder Pain", "Elbow Injury", "Revision Surgery"],
    fellowships: "Mayo Clinic Travelling Fellowship (USA), FRCS (UK).",
    qualifications: "FRCS (UK), CCT (UK), MSc Ortho Engineering, MS Ortho, MBBS.",
    specialties: [
      "Advanced Latarjet Procedures (Shoulder)",
      "Complex Multiligament Elbow Reconstructions",
      "Revision Joint Replacement Mastery",
      "Structural Hand & Wrist Reconstruction"
    ]
  },
  "amith-reddy": {
    name: "Dr. Amith Reddy",
    role: "Lead – Robotic Knee & Hip Arthroplasty Program",
    unitName: "Robotic Arthroplasty Unit",
    platform: "MAKO Robotic Arthroplasty Specialist",
    specificVolume: "3,500+ Robotic Knee Replacements",
    title: "Senior Consultant – Lower Limb & Robotic Arthroplasty",
    focus: "Master of Stryker Mako 4.0 & Advanced Robotic Alignment",
    image: "/doctors/doc_amith.png",
    appointmentLink: "https://www.apollo247.com/doctors/dr-amith-reddy-2e52461a-23f3-4eb6-bc09-8d3e6c93bdeb?source=Listing_Page",
    bio: "Dr. Amith Reddy is the lead architect of robotic surgical precision at Apollo Hospitals. Specializing in the lower limb (Hip & Knee), he brings a staggering record of over 10,000 successful procedures. His clinical discipline is defined by dual certifications from Swiss Olympic (Switzerland) and ISAKOS (Spain), ensuring high-velocity recovery for arthroplasty patients.",
    experience: "19+ Years",
    procedures: "10,000+",
    conditions: ["Knee Arthritis", "Hip Replacement", "Robotic Surgery"],
    fellowships: "FIJR (Swiss Olympic), FSM (ISAKOS Spain).",
    qualifications: "MBBS, PGD, DNB, MNAMS, M.Ch (Orthopaedic Surgery).",
    specialties: [
      "Stryker Mako 4.0 Robotic-Arm Assisted Surgery",
      "Total Knee & Hip Arthroplasty",
      "Virtual Range of Motion (vROM) Simulation",
      "Advanced Revision Total Joints"
    ]
  },
  "nitish-bhan": {
    name: "Dr. Nitish Bhan",
    role: "Lead – DAA Hip & Pelvic Reconstruction",
    unitName: "Robotic Arthroplasty Unit",
    platform: "DAA Muscle-Sparing Specialist",
    specificVolume: "2,000+ Direct Anterior Hip Replacements",
    title: "Senior Consultant – Pelvic & Hip Reconstruction",
    focus: "Pioneer in Direct Anterior Approach & Pelvic Trauma care",
    image: "/doctors/doc_nitish.png",
    appointmentLink: "https://www.apollo247.com/doctors/dr-nitish-bhan-13ebe5f0-8b45-4996-b5bb-dd75bf0b2701?source=Listing_Page",
    bio: "Dr. Nitish Bhan specializes in the most complex quadrant of the human frame: the Pelvis and Hip. He is renowned for introducing advanced minimally invasive protocols, including the Direct Anterior Approach (DAA) Hip Replacement, which eliminates muscle damage. His expertise in pelvic and acetabular trauma care is recognized across the national healthcare landscape.",
    experience: "18+ Years",
    procedures: "8,000+",
    conditions: ["Hip Replacement", "Pelvic Pain", "Knee Arthritis"],
    fellowships: "Joint Replacement Fellowships (Singapore & China).",
    qualifications: "MBBS, DNB, M.Ch, MNAMS.",
    specialties: [
      "Pelvic & Acetabular Trauma Reconstruction",
      "Direct Anterior Approach (DAA) Hip Replacement",
      "Tactileless & Computer Navigated Hip Surgery",
      "Complex Revision Hip Arthroplasty"
    ]
  },
  "ravi-teja-rudraraju": {
    name: "Dr. Ravi Teja Rudraraju",
    role: "Lead – Joint Preservation & Ortho-Biologics",
    unitName: "Joint Preservation & Sports Medicine Unit",
    platform: "Arthrex Synergy UHD4 Faculty",
    specificVolume: "1,500+ Biological Joint Restorations",
    title: "Chief of Joint Preservation & Sports Medicine",
    focus: "Expert in Advanced 4K UHD4 Imaging & Ortho-Biologics",
    image: "/doctors/doc_ravi.png",
    appointmentLink: "https://www.apollo247.com/doctors/dr-ravi-teja-rudraraju-247ed099-b1e4-4fb0-89e6-93212cc819eb?source=Listing_Page",
    bio: "Dr. Ravi Teja Rudraraju leads the Joint Preservation unit, specializing in high-definition arthroscopic reconstruction using the Arthrex Synergy UHD4 4K system. His practice focuses on biological restoration using high-concentration PRP and Stem Cell therapies to delay or avoid artificial joint replacement. Extensively trained at the Geisinger Clinic (USA), he is at the forefront of regenerative tissue engineering.",
    experience: "12+ Years",
    procedures: "5,000+",
    conditions: ["Sports Injury", "Knee Pain", "Joint Preservation"],
    fellowships: "Sports Medicine Fellow (Geisinger, USA), Arthrex Technology Lead.",
    qualifications: "MBBS, MS (Orthopedics), Arthrex Synergy SDK Specialist.",
    specialties: [
      "Arthrex Synergy UHD4 4K Visualization",
      "Ortho-Biologics (PRP, BMAC & Stem Cell Therapy)",
      "Biological Joint Preservation (Knee)",
      "High-Performance Sports Medicine"
    ]
  },
  "harsha-vardhana-reddy": {
    name: "Dr. B. Harsha Vardhana Reddy",
    role: "Lead – Sports Traumatology & Athletic Recovery",
    unitName: "Joint Preservation & Sports Medicine Unit",
    platform: "VALD Performance Lead",
    specificVolume: "800+ Athletic Shoulder Repairs",
    title: "Consultant – Upper Limb & Sports Performance",
    focus: "VALD Performance Lead for Athletic Recovery & Restoration",
    image: "/doctors/doc_harsha.png",
    appointmentLink: "https://www.apollo247.com/doctors/dr-b-harsha-vardhana-reddy-51807eec-1507-467c-91fb-4c6b2cb599ff?source=Listing_Page",
    bio: "Dr. Harsha Vardhana Reddy bridges the gap between surgical repair and elite athletic performance. He is the lead surgeon for the VALD Performance Centre at Precision Orthopaedics, utilizing ForceDecks and DynaMo data to ensure zero-compromise return-to-sport clearance. He specializes in Upper Limb sports injuries and highly precise arthroscopic repairs.",
    experience: "10+ Years",
    procedures: "3,000+",
    conditions: ["Sports Injury", "Shoulder Pain", "Elbow Injury"],
    fellowships: "Fellowship in Arthroplasty, VALD Performance Certified Lead.",
    qualifications: "MBBS, MS (Ortho), Fellowship in Sports Medicine.",
    specialties: [
      "VALD ForceDecks Biomechanical Assessment",
      "Upper Limb Sports Traumatology",
      "Athletic Return-to-Sport Protocols",
      "Computer-Assisted Ligament Reconstruction"
    ]
  },
  "prashanth-reddy-a": {
    name: "Dr. Prashanth Reddy A",
    role: "Consultant – Hip & Pelvic Reconstruction",
    unitName: "Robotic Arthroplasty Unit",
    platform: "Wrightington UK Trauma Protocol faculty",
    specificVolume: "1,200+ Complex Pelvic Reconstructions",
    title: "Consultant – Hip & Pelvic Reconstruction",
    focus: "UK-Trained Specialist in Adult Joint & Pelvic Reconstruction",
    image: "/doctors/doc_prashanth.png",
    appointmentLink: "https://www.apollo247.com/doctors/dr-prashanth-reddy-a-3d44af2a-78a0-4980-a3ce-f504d0b818d3?source=Listing_Page",
    bio: "Dr. Prashanth Reddy A is a specialist surgeon with deep expertise in Hip and Knee surgical interventions. Having served as a Senior Clinical Fellow at Wrightington Hospital (UK), he integrates elite Western trauma protocols into complex adult reconstructions, offering a comprehensive solution for patients with advanced joint degeneration involving the hip and pelvis.",
    experience: "13+ Years",
    procedures: "4,000+",
    conditions: ["Hip Replacement", "Pelvic Pain", "Trauma"],
    fellowships: "Senior Clinical Fellow (Wrightington Hospital, UK), Complex Arthroplasty Fellow.",
    qualifications: "MBBS, DNB Ortho, M.Ch (Hip & Knee Surgery - UK).",
    specialties: [
      "Complex Hip and Knee Replacement",
      "Pelvic Trauma & Reconstruction",
      "Adult Joint Revision Arthroplasty",
      "Musculoskeletal Trauma Care"
    ]
  }
};
