export const specialistData = {
  "best-orthopedic-doctor-in-hyderabad": {
    targetDoctorSlug: "deepthi-nandan-reddy",
    searchIntent: "Seeking the highest overall authority in Orthopaedics in the city.",
    h1: "Best Orthopedic Doctor in Hyderabad",
    subtitle: "Precision Surgical Board Leadership | UK CCT & Mayo Clinic Pedigree",
    seoKeywords: "best orthopedic doctor in hyderabad, top 10 orthopedic surgeons, best bone specialist",
    validationPoints: [
      "Former President, Shoulder & Elbow Society of India (SESI)",
      "UK Certificate of Completion of Training (CCT)",
      "Over 30 Years of Complex Reconstructive Experience",
      "HOD, Precision Orthopaedics at Apollo Hospitals"
    ]
  },
  "best-knee-replacement-surgeon-in-hyderabad": {
    targetDoctorSlug: "amith-reddy",
    searchIntent: "Seeking a sub-specialist for joint replacement, specifically modern/robotic techniques.",
    h1: "Best Knee Replacement Surgeon in Hyderabad",
    subtitle: "Pioneer in Stryker Mako 4.0 Sub-millimeter Robotic Arthroplasty",
    seoKeywords: "best knee replacement surgeon hyderabad, robotic knee surgeon, top joint replacement doctor",
    validationPoints: [
      "Over 10,000 Joint Replacement Surgeries Performed",
      "3,500+ Mako Robotic Knee Surgeries (Highest Volume in Region)",
      "International Fellowships in Switzerland & Spain",
      "Lead, Robotic Arthroplasty Unit"
    ]
  },
  "best-shoulder-surgeon-in-hyderabad": {
    targetDoctorSlug: "deepthi-nandan-reddy",
    searchIntent: "Seeking an expert for complex shoulder issues, sports injuries, or reverse replacements.",
    h1: "Best Shoulder Surgeon in Hyderabad",
    subtitle: "Internationally Recognized Authority in Complex Shoulder Reconstruction",
    seoKeywords: "best shoulder surgeon hyderabad, rotator cuff specialist, top shoulder replacement doctor",
    validationPoints: [
      "Mayo Clinic Travelling Fellow (USA)",
      "4,000+ Complex Shoulder Reconstructions",
      "NHS Consultant Pedigree (UK)",
      "Mastery of Reverse Total Shoulder Arthroplasty (RTSA)"
    ]
  },
  "top-hip-replacement-doctor": {
    targetDoctorSlug: "nitish-bhan",
    searchIntent: "Seeking muscle-sparing, rapid-recovery hip replacement.",
    h1: "Top Hip Replacement Doctor in Hyderabad",
    subtitle: "Master of Muscle-Sparing Direct Anterior Approach (DAA)",
    seoKeywords: "best hip replacement doctor hyderabad, DAA hip surgeon, avascular necrosis specialist",
    validationPoints: [
      "2,000+ Direct Anterior Hip Replacements",
      "Zero Muscle Detachment Protocol",
      "Fellowships in Joint Replacement from Singapore & China",
      "Lead, DAA Hip & Pelvic Reconstruction"
    ]
  },
  "best-sports-medicine-doctor": {
    targetDoctorSlug: "ravi-teja-rudraraju",
    searchIntent: "Seeking treatment for athletic injuries, ligament tears, and joint preservation.",
    h1: "Best Sports Medicine Doctor in Hyderabad",
    subtitle: "Advanced Arthroscopy & Ortho-Biologics Expert",
    seoKeywords: "best sports medicine doctor hyderabad, ACL surgeon, meniscus tear specialist",
    validationPoints: [
      "Arthrex Synergy UHD4 Faculty",
      "1,500+ Biological Joint Restorations",
      "Geisinger Clinic (USA) Fellowship",
      "Chief of Joint Preservation Unit"
    ]
  },
  "best-arthroscopic-surgeon-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-arthroscopy-clinic-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-clinic-for-spine-surgery-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "lower-back-pain-doctor": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "lower-back-pain-specialist-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "lower-back-pain-specialist-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-arthroscopy-doctor-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-orthopedic-specialist-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "arthroscopic-surgeons-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-shouldre-pain-doctor-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-clinic-for-ligament-injury-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-doctors-for-ligament-injury-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-ligament-injury-specialist-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-treatment-for-ligament-injuries": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "ankle-injury-treatment-doctors-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-clinic-for-leg-sprain-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-orthopaedic-doctor-for-ankle-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-surgery-and-treatment-in-hyderabad-for-ankle-sprain": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-orthopedic-clinic-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "physiotherapist-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-orthopedic-specialist-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-clinic-for-rheumatoid-arthritis-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-keyhole-surgeon-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-laparoscopic-surgeon-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-stem-cell-therapy-treatment-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "physiotherapy": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-clinic-for-osteoarthritis-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-clicnic-for-rotator-cuff-treatment-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-doctor-for-rotator-cuff-treatment-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-exercises-for-rotator-cuff-problems": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-treatment-for-rotator-cuff-injury-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-orthopedic-treatment-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-child-orthopedic-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-doctor-for-pediatric-orthopedician": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "stem-cell-therapy-doctors-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "orthopedic-specialist-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "solution-for-rotator-cuff-surgery-doctor": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "solution-for-rotator-cuff-surgery-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "rotator-cuff-injury-treatment-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-general-orthopaedic-diagnosis-treatment-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-prp-treatment-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "prp-doctors-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "prp-treatment-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-arthroscopic-surgeon-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-orthopedic-surgeon-for-arthroscopic-treatment-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "postoperative-complications": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "when-should-i-see-a-doctor": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "postoperative-physical-therapy-for-rotator-cuff-injury": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-orthopedic-hospital-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "orthopedic-hospital-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-doctor-of-rotator-cuff-surgery-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-hospital-for-rotator-cuff-surgery-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "rotator-cuff-surgeon-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "physiotherapist-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "physiotherapy-clinic-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "physiotherapy-cost-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "physiotherapy-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-orthopaedic-surgeon-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "osteoarthritis-specialist-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-orthopedic-surgeon-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "rotator-cuff-injury-treatment-doctors-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "rotator-cuff-repair-treatment-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "rotator-cuff-specialist-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "rotator-cuff-pain-treatment-doctors-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-doctor-for-rotator-cuff-tear-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-orthopedic-centre-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-orthopedic-physiotherapist-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-orthopedics-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "arthroscopic-rotator-cuff-repair-clinic-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-arthroscopic-rotator-cuff-tear-doctor-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-orthopaedic-centre-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-rotator-cuff-tear-surgery-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-rotator-cuff-tear-treatment-hospitals-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "top-rotator-cuff-surgery-doctors-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "a-best-orthopedic-hospital-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "the-best-orthopedic-doctor-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "top-orthopedic-doctors-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "arthroscopic-rotator-cuff-repair-clinic-near": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-arthroscopic-rotator-cuff-repair-doctor-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "rotator-cuff-tear-exercises-specialist-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-ortho-clinic-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-ortho-doctor-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "orthopedic-center-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "orthopedic-specialist-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "orthopedic-surgeon-clinic-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "orthopedic-surgeon-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "orthopedic-surgeon-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "orthopedic-surgery-doctor-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "orthopedic-surgery-hospital-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-broken-bone-treatment-hospital-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "rotator-cuff-surgery-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-orthopedic-doctor-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-orthopedician-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "orthopedic-clinic-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "orthopedic-doctor-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "orthopedic-doctor-in-hyderabad-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "rotator-cuff-repair-hospital-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "rotator-cuff-repair-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "rotator-cuff-repair-operation-clinic-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "rotator-cuff-repair-physiotherapy-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-physical-therapy-treatment-cost-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-physical-therapy-treatment-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-physiotherapist-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-physiotherapist-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "physiotherapy-clinic-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "physiotherapy-hospital-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "physiotherapy-hospital-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-rotator-cuff-surgery-doctor-in-hyderabad": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "rotator-cuff-surgery-cost-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "rotator-cuff-treatment-near-me": { aliasOf: "best-orthopedic-doctor-in-hyderabad" },
  "best-shoulder-replacement-surgeon-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-replacement-surgeon": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "total-shoulder-replacement-surgery-clinic-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-replacement-surgeon": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-arthroscopy-doctor-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-clinic-for-broken-shoulder-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-clinic-for-shoulder-surgery-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-physiotherapist-near-me-for-shoulder-problem": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-physitherapy-clinic-for-shoulder-pain-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-pain-treatment-clinic-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "orthopedic-doctor-for-shoulder-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-arthroscopy-doctors-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-replacement-surgeon-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-clinic-for-dislocated-shoulder-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-dislocation-treatment-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "dislocation-shoulder-clinic-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-doctor-for-frozen-shoulder-in-hyderabd": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-orthopedic-surgeon-for-frozen-shoulder-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-treatment-for-frozen-shoulder-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "frozen-shoulder-specialist-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "frozen-shoulder-treatment-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-dislocation-surgeon-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-dislocation-surgery-treatment-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-dislocation-treatment-doctors-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-clinic-for-keyhole-shoulder-surgery-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "top-things-you-should-know-about-shoulder-dislocation-injuries": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-doctor-for-shoulder-pain-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-surgeon-for-shoulder-operation-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-dislocation-surgeon-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-replacement-surgery-clinic-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "physiotherapy-for-shoulder-pain": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-exercises-for-frozen-shoulder-pain-relief": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "physiotherapy-exercises-for-frozen-shoulder": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-clinic-for-shoulder-sprain-treatment-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-doctors-for-shoulder-sprain-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-sprain-therapy-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "dislocated-shoulder-clinic-for-children-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-arthroscopy-for-rotator-cuff-tear-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "trained-shoulder-surgeon": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-arthritis-clinic-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-pain-treatment-near-me-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-physiotherapist-for-shoulder-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-exercises": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-exercises-for-women": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-physio-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-physiotheraphic-in-hydrerbad-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "the-best-top-shoulder-strengthening-exercises": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-clinic-for-shoulder-join-treatment-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-join-replacement-surgeon-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-joint-replacement-doctors-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-clinic-for-reverse-shoulder-replacement-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-reverse-shoulder-replacement-surgeon-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-clinic-for-frozen-shoulder-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-frozen-shoulder-treatment-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-specialist-for-frozen-shoulder-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-surgeron-for-frozen-shoulder-treatment-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-arthroscopic-shoulder-treatment-surgeon-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-rotator-cuff-injury-treatment-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-rotator-cuff-treatment-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "hyderabad-shoulder-clinic": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-sleeping-tips-after-shoulder-surgery": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "dislocated-shoulder-treatment-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-dislocation-physiotherapy": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-dislocation-physiotherapy-treatment-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-pain-treatment-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-orthopedic-doctor-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "frozen-shoulder-specialist-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "physiotherapy-treatment-for-frozen-shoulder": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-clinic-for-shoulder-arthritis-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-arthritis-surgery-doctors-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-pain-doctors-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-pain-specialist-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-specialist-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-surgeon-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "arthroscopic-shoulder-decompression-surgeon-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "arthroscopy-for-shoulder-dislocation-clinic-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-dislocation-physiotherapy-clinic-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-joint-dislocation-surgeon-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-reduction-surgery-clinic-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-frozen-shoulder-surgery-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-sleeping-position-for-shoulder": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-sleeping-positions-for-shoulder-pain": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-arthroscopic-shoulder-clinic-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-doctor-for-shoulder-arthroscopic-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-doctor-dislocated-shoulder-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "physical-therapy-for-dislocated-shoulder-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-orthopedic-shoulder-specialist-near": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-fracture-clinic-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-fracture-surgery-doctor-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "frozen-shoulder-treatment-doctor-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-orthopedic-hospital-for-shoulder-pain-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-doctors-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-pain-treatment-specialists-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-specialists-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-specialists-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-arthroscopy-doctor-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "frozen-shoulder-doctor-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "fractured-shoulder-treatment-doctor-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "frozen-shoulder-physiotherapy-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "frozen-shoulder-physiotherapy-treatment-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-instability-treatment-physiotherapy": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "arthroscopic-shoulder-surgeon-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "arthroscopic-shoulder-surgery-clinic-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "arthroscopic-shoulder-surgery-doctors-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "arthroscopic-shoulder-surgery-hospital-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "arthroscopic-shoulder-surgery-specialist-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-dislocation-clinic-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-dislocation-clinical-features": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-dislocation-doctor-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-dislocation-surgery-doctor-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-dislocation-surgery-specialist-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-rotator-cuff-repair-clinic-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-rotator-cuff-surgery-specialist-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-rotator-cuff-tear-hospital-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-rotator-cuff-tear-hospital-in-hyderabad-arthroscopic-superior-capsular-reconstruction-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "arthroscopic-shoulder-surgery-specialists-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-arthroscopic-shoulder-surgeon-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-physiotherapist-after-shoulder-joint-replacement-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-joint-replacement-postoperative-care": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-joint-replacement-surgery-hospital-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-clinic-for-shoulder-fracture-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-physiotherapy-doctor-for-shoulder-fracture-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-dislocation-doctor-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-specialist-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-arthroscopy-surgery-hospital-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-rotator-cuff-tear-hospital-in-hyderabadrotator-cuff-surgery-cost-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-replacement-surgery-doctors-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-replacement-surgery-doctors-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-replacement-surgery-hospital-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-replacement-surgery-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-treatment-for-shoulder-tendonitis": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-dislocation-doctors-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-surgeon-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-replacement-surgery-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-specialist-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-replacement-surgeons-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-joint-replacement-surgery-doctor-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-orthopedic-doctor-near-me-for-shoulder-pain": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-orthopedic-for-shoulder-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-replacement-surgeons-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-specialist-doctor-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-frozen-shoulder-treatment-hospital-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "doctors-for-frozen-shoulder-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "doctors-of-shoulder-surgeon-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-replacement-hospital-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-dislocated-surgeon-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-dislocated-surgeons-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-dislocated-hospital-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-dislocated-surgeons-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-surgeons-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-surgery-hospital-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "best-shoulder-injury-doctor-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-injuries-treatment-doctors-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-injuries-treatment-hospital-in-hyderabad": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-injuries-treatment-in-childrens-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-injury-doctor-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-injury-physiotherapy-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "shoulder-injury-therapy-near-me": { aliasOf: "best-shoulder-surgeon-in-hyderabad" },
  "acl-reconstruction-surgeon-in-hyderabad": { aliasOf: "best-knee-replacement-surgeon-in-hyderabad" },
  "best-acl-reconstruction-surgery-clinic-in-hyderabad": { aliasOf: "best-knee-replacement-surgeon-in-hyderabad" },
  "best-knee-ligament-reconstruction-surgery-doctor-in-hyderabad": { aliasOf: "best-knee-replacement-surgeon-in-hyderabad" },
  "knee-arthroscopy-doctors-in-hyderabad": { aliasOf: "best-knee-replacement-surgeon-in-hyderabad" },
  "knee-arthroscopy-surgeon-in-hyderabad": { aliasOf: "best-knee-replacement-surgeon-in-hyderabad" },
  "orthopedic-doctor-for-knee-in-hyderabad": { aliasOf: "best-knee-replacement-surgeon-in-hyderabad" },
  "acl-tear-doctors-near-me": { aliasOf: "best-knee-replacement-surgeon-in-hyderabad" },
  "best-clinic-for-acl-tear-treatment": { aliasOf: "best-knee-replacement-surgeon-in-hyderabad" },
  "sports-injuries-knee-specialist-in-hyderabad": { aliasOf: "best-knee-replacement-surgeon-in-hyderabad" },
  "best-orthopedic-doctor-for-sports-injuries-near-me": { aliasOf: "best-sports-medicine-doctor" },
  "sports-orthopedic-doctor-near-me": { aliasOf: "best-sports-medicine-doctor" },
  "best-sports-injury-doctor-in-hyderabad-near-me": { aliasOf: "best-sports-medicine-doctor" },
  "best-sports-injury-doctor-in-hyderabad": { aliasOf: "best-sports-medicine-doctor" },
  "best-sports-orthopedic-doctor-near-me": { aliasOf: "best-sports-medicine-doctor" },
  "sports-injury-clinic-near-me": { aliasOf: "best-sports-medicine-doctor" },
  "sports-orthopedic-surgeon-in-hyderabad": { aliasOf: "best-sports-medicine-doctor" },
  "best-sports-injuries-hospital-hyderabad": { aliasOf: "best-sports-medicine-doctor" },
  "sports-injuries-doctor-in-hyderabad": { aliasOf: "best-sports-medicine-doctor" },
  "sports-injuries-doctors-near-me": { aliasOf: "best-sports-medicine-doctor" },
  "sports-injury-specialist-near-me": { aliasOf: "best-sports-medicine-doctor" },
  "sports-orthopedic-near-me": { aliasOf: "best-sports-medicine-doctor" },
  "sports-physiotherapist-in-hyderabad": { aliasOf: "best-sports-medicine-doctor" },
  "best-sports-injury-doctor-near-me": { aliasOf: "best-sports-medicine-doctor" },
  "sports-injuries-treatment-doctors-in-hyderabad": { aliasOf: "best-sports-medicine-doctor" },
  "sports-injuries-treatment-hospital-in-hyderabad": { aliasOf: "best-sports-medicine-doctor" },
  "sports-injuries-treatment-near-me": { aliasOf: "best-sports-medicine-doctor" },
  "sports-injury-doctor-near-me": { aliasOf: "best-sports-medicine-doctor" },
  "sports-injury-physiotherapy-near-me": { aliasOf: "best-sports-medicine-doctor" },
  "sports-injury-therapy-near-me": { aliasOf: "best-sports-medicine-doctor" },
};
